title: "The Scrawl theme"
description: >-
  A theme for [Jekyll](https://jekyllrb.com/)
  based on
  [Primer](https://github.com/pages-themes/primer)

sass:
  style: compressed

exclude:
  - _site
  - '*.gem'
  - '*.gemspec'
  - 'Gemfile*'
  - bin
  - docker-compose.yml
  - LICENSE
  - Makefile

plugins:
  # force included by GitHub Pages
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # required by {% seo %} tag
  - jekyll-seo-tag

permalink: pretty
